export const LOGIN = 'LOGIN';
export const SIGN_IN = 'SIGN_IN';
export const LOG_OUT = 'LOG_OUT';

export const SAVE_POST = 'SAVE_POST';
export const FETCH_POSTS = 'FETCH_POSTS';

export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';

export const START_SIGNIN_ERROR = 'START_SIGNIN_ERROR';
export const END_SIGNIN_ERROR = 'END_SIGNIN_ERROR';

export const START_LOGIN_ERROR = 'START_LOGIN_ERROR';
export const END_LOGIN_ERROR = 'END_LOGIN_ERROR';

export const START_FETCHPOST_ERROR = 'START_FETCHPOST_ERROR';
export const END_FETCHPOST_ERROR = 'END_FETCHPOST_ERROR';